Project_Webshop/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Models
{
    public class Customer
    {
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Number { get; set; }
        public string Postcode { get; set; }
        public string Password { get; set; }

        
        public string DeliveryAddress { get; set; }
        public Newsletter Newsletter;
        public ICollection<Order>Orders { get; set; }

    }
}

Project_Webshop/Models/ErrorViewModel.cs
using System;

namespace Project_Webshop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project_Webshop/Models/Newsletter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Models
{
    public class Newsletter
    {
        public int NewsletterID { get; set; }
        public Customer Customer { get; set; }

       
    }
}

Project_Webshop/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Models
{
    public class Order
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Customer customer { get; set; }

       // public virtual ICollection<Orderline> Orderlines { get; set; }


    }
}

Project_Webshop/Models/Orderline.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Models
{
    public class Orderline
    {
        public int OrderlineID { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }

        [Column(TypeName = "decimal(18,4)")]
        public Decimal Price { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public Decimal Amount  { get; set; }

  

        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }

    }
}

Project_Webshop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Models
{
    public class Product
    {

        public int ProductID { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public Decimal Price { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public Decimal Quantity { get; set; }
        public bool Discount { get; set; }
        public bool Favorite { get; set; }
        //Orderline Orderline { get; set; }

        //public virtual ICollection<Orderline> Orderlines { get; set; }

    }
}

Project_Webshop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project_Webshop/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Controllers
{
    public class CustomerController
    {
        // text controller
    }
}

Project_Webshop/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Controllers
{
    public class DiscountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project_Webshop/Controllers/FaqController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Controllers
{
    public class FaqController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Project_Webshop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Project_Webshop.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Project_Webshop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Webshop.Models;
using Project_Webshop.Viewmodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_Webshop.Controllers
{
    public class ProductController : Controller
    {
        public List<Product> productSweater;
        public List<Product> productTshirt;
        public List<Product> mug;
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Tshirt()
        {
            ProductListViewModel viewModel = new ProductListViewModel();
            viewModel.Producten = productTshirt;
            return View(viewModel);
        }
        public IActionResult Mug()
        {
            ProductListViewModel viewModel = new ProductListViewModel();
            viewModel.Producten = mug;
            return View(viewModel);
        }
        public IActionResult Sweater()
        {
            ProductListViewModel viewModel = new ProductListViewModel();
            viewModel.Producten = productSweater;
            return View(viewModel);
        }
        public ProductController()
        {
            productSweater = new List<Product>();
            productSweater.Add(new Product() { Color = "Black", Price = 25, Discount = true, Favorite = false, Quantity = 1, Size = "M", ProductID = 1 });
            productSweater.Add(new Product() { Color = "Lemon", Price = 35, Discount = false, Favorite = false, Quantity = 2, Size = "S", ProductID = 2 });
            productSweater.Add(new Product() { Color = "Purple", Price = 35, Discount = false, Favorite = false, Quantity = 5, Size = "XL", ProductID = 3 });
            productSweater.Add(new Product() { Color = "Royal Blue", Price = 25, Discount = true, Favorite = false, Quantity = 3, Size = "L", ProductID = 4 });
            productSweater.Add(new Product() { Color = "Slate Red", Price = 35, Discount = false, Favorite = false, Quantity = 1, Size = "M", ProductID = 5 });




            productTshirt = new List<Product>();
            productTshirt.Add(new Product() { Color = "Black", Price = 15, Discount = true, Favorite = false, Quantity = 4, Size = "M", ProductID = 6 });
            productSweater.Add(new Product() { Color = "Lemon", Price = 35, Discount = false, Favorite = false, Quantity = 2, Size = "S", ProductID = 7 });
            productSweater.Add(new Product() { Color = "Purple", Price = 35, Discount = false, Favorite = false, Quantity = 5, Size = "L", ProductID = 8 });
            productSweater.Add(new Product() { Color = "Royal Blue", Price = 25, Discount = false, Favorite = false, Quantity = 5, Size = "M", ProductID = 9 });
            productSweater.Add(new Product() { Color = "Slate Red", Price = 35, Discount = false, Favorite = false, Quantity = 1, Size = "XXL", ProductID = 10 });


            mug = new List<Product>();
            productSweater.Add(new Product() { Color = "White", Price = 15, Discount = false, Favorite = false, Quantity = 10, Size = "", ProductID = 11 });
            productSweater.Add(new Product() { Color = "White", Price = 20, Discount = false, Favorite = false, Quantity = 15, Size = "", ProductID = 12 });
         

        }
    }
}

Project_Webshop/Views/Contact/Index.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "Contact";
}



<div class="text-center">
    <p> Welcome to the Contact page!</p> 
</div>

Project_Webshop/Views/Discount/Index.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "Discount";
}



<div class="text-center">
    <p>Welcome to the discount page!</p>  
</div>

Project_Webshop/Views/FAQ/Index.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "FAQ";
}



<div class="text-center">
    <p>Welcome to the FAQ page!</p> 
</div>

Project_Webshop/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "Home Page";
}

<div class="container text-center">

    <h1>Welcome</h1>


    <img class="img-fluid" src="~/images/IndexLogo.png" alt="logo with background lights" />
   



    <p class="text-center">
        Hi everyone and welcome to my brand new webshop.
    </p> <p class="text-center">
    Here you will find the latest merch
    so you can wear it in your school at home or at a wedding.
</p>
       
    
</div>

Project_Webshop/Views/Product/Index.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "Product";
}



<div class="container text-center">
    <p>Welcome to the Merch!</p>

    <div class="row">
        <div class="card col card-deck" style="width: 18rem;">
            <img src="./images/Sweaters/Sweater_RoyalBlue_Front.png" class="card-img-top" alt="Sweater">
            <div class="card-body">
                <p class="card-text"><a asp-controller="Product" asp-action="Sweater">Check our cool Sweaters</a></p>
            </div>
        </div>
        <div class="card col card-deck" style="width: 18rem;">
            <img src="./images/T-shirts/Tshirt_Slate(Red)_Front.png" class="card-img-top" alt="T-shirt">
            <div class="card-body">
                <p class="card-text"><a asp-controller="Product" asp-action="Tshirt">A T-shirt with your favorite wolfie</a></p>
            </div>
        </div>

        <div class="card col card-deck" style="width: 18rem;">
            <img src="./images/Cups/Cup_Coffee.png" class="card-img-top" alt="T-shirt">
            <div class="card-body">
                <p class="card-text"><a asp-controller="Product" asp-action="Mug">For all our coffee lovers Choose your mug!</a></p>
            </div>
        </div>
    </div>
</div>

Project_Webshop/Views/Product/Mug.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "Mug";
}

<div class="text-center container row">

    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/Mugs/Cup_Bee.png" class="card-img-top" alt="mug">
        <div class="card-body">
            <h2>Bee Mug</h2>
            <p class="card-text">15 € </p>
        </div>
    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/Mugs/Cup_Coffee.png" class="card-img-top" alt="mug">
        <div class="card-body">
            <h2>Coffee Mug</h2>
            <p class="card-text">10 € </p>
        </div>
    </div>

    </div>

Project_Webshop/Views/Product/Sweater.cshtml
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "Sweater";
}

<div class="text-center container row">

    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/Sweaters/Sweater_Black_Front.png" class="card-img-top" alt="sweater">
        <div class="card-body">
            <h2>Black Sweater</h2>
            <p class="card-text">25 € </p>
        </div>
    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images//Sweaters/Sweater_Lemon_Front.png" class="card-img-top" alt="sweater">
        <div class="card-body">
            <h2>Lemon Sweater</h2>
            <p class="card-text">25 € </p>
        </div>
    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/Sweaters/Sweater_Purple_Front.png" class="card-img-top" alt="sweater">
        <div class="card-body">
            <h2>Purple Sweater</h2>
            <p class="card-text">25 €</p>
        </div>
    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/Sweaters/Sweater_RoyalBlue_Front.png" class="card-img-top" alt="sweater">
        <div class="card-body">
            <h2>Royal Blue Sweater</h2>
            <p class="card-text">25 € </p>
        </div>
    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/Sweaters/Sweater_Slate(red)_Front.png" class="card-img-top" alt="sweater">
        <div class="card-body">
            <h2>Slate Red Sweater</h2>
            <p class="card-text">25 € </p>
        </div>
    </div>
  

</div>

Project_Webshop/Views/Product/Tshirt.cshtml
@model Project_Webshop.Viewmodel.ProductListViewModel
@{
    Layout = "~/Views/Shared/_WebshopLayout.cshtml";
    ViewData["Title"] = "T-shirts";
}


<div class="text-center container row">




    <div class="card col-3" style="width: 18rem;">


            <img src="~/images/T-shirts/Tshirt_Black_Front.png" class="card-img-top" alt="tshirts">
            <h2> Black T-shirt</h2>
            @*@Html.DropDownList(product.Size)*@
            <p class="card-text">25 €</p>
            <button class="btn btn-success">Buy</button>
       
    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images//T-shirts/Tshirt_Lemon_Front.png" class="card-img-top" alt="tshirts">

        <h2>Lemon T-shirt</h2>
        <p class="card-text">25 € </p>
        <button class="btn btn-success">Buy</button>

    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/T-shirts/Tshirt_Purple_Front.png" class="card-img-top" alt="tshirts">

        <h2>Purple T-shirt</h2>
        <p class="card-text">25 € </p>
        <button class="btn btn-success">Buy</button>

    </div>

    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/T-shirts/Tshirt_RoyalBlue_Front.png" class="card-img-top" alt="tshirts">
        <h2>Blue T-shirt</h2>
        <p class="card-text">25 € </p>
        <button class="btn btn-success">Buy</button>


    </div>
    <div class="card col-3" style="width: 18rem;">
        <img src="~/images/T-shirts/Tshirt_Slate(Red)_Front.png" class="card-img-top" alt="tshirts">
     
            <h2>Red T-shirt</h2>
            <p class="card-text">25 € </p>
            <button class="btn btn-success">Buy</button>
       

    </div>
</div>

Project_Webshop/Views/Shared/_WebshopLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Webshop</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-light navbar-expand-md bg-light justify-content-md-center justify-content-start">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <img class="logo" src="~/images/logo_png.png" alt="Logo" />
            </a>
            <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
                <ul class="navbar-nav mx-auto text-md-center text-left">
                    <li class="nav-item">
                        <a class="nav-link navbar-brand mx-0 d-none d-md-inline" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-brand mx-0 d-none d-md-inline" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-brand mx-0 d-none d-md-inline" asp-area="" asp-controller="Discount" asp-action="Index">Discount</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-brand mx-0 d-none d-md-inline" asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link navbar-brand mx-0 d-none d-md-inline" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>

                    </li>
                </ul>
                <ul class="nav navbar-nav flex-row justify-content-md-center justify-content-start flex-nowrap">
                    <li style="padding-left: 10px" class="nav-item"> <a href="#"> <i class="fas fa-shopping-cart"></i>  </a>  </li>

                    <li style="padding-left: 10px" class="nav-item"> <a href="#"> <i class="fas fa-user"></i>  </a>  </li>
                </ul>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Footer -->
    <footer class="border-top footer text-muted color-footer">
        <div class="container">
            <span>Follow me on</span> <a href="https://twitter.com/LordDries" target="_blank"><i class="fab fa-twitter"></i></a>
            <span>Made with </span>
            <span><i class="fas fa-heart"></i></span>

            <span class="footer-right"> Dries Mangelschots</span>

            <span class="footer-right">Made by </span>


        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>